// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | RichTextSlice
  | HeroSlice
  | FeaturesGridSlice
  | CtaBannerSlice
  | FooterSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *CTABanner → Default → Primary*
 */
export interface CtaBannerSliceDefaultPrimary {
  /**
   * Headline field in *CTABanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ready to Join?
   * - **API ID Path**: cta_banner.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Description field in *CTABanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Join the movement and make an impact...
   * - **API ID Path**: cta_banner.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Text field in *CTABanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Join Now
   * - **API ID Path**: cta_banner.default.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Button Link field in *CTABanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for CTABanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default CTABanner variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CTABanner*
 */
type CtaBannerSliceVariation = CtaBannerSliceDefault;

/**
 * CTABanner Shared Slice
 *
 * - **API ID**: `cta_banner`
 * - **Description**: Gradient CTA banner with headline, description, and primary button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSlice = prismic.SharedSlice<
  "cta_banner",
  CtaBannerSliceVariation
>;

/**
 * Item in *FeaturesGrid → Default → Primary → Features*
 */
export interface FeaturesGridSliceDefaultPrimaryFeaturesItem {
  /**
   * Icon field in *FeaturesGrid → Default → Primary → Features*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: features_grid.default.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "Network" | "Vision" | "Movement" | "Globe" | "Users" | "Rocket"
  >;

  /**
   * Title field in *FeaturesGrid → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Connect Globally
   * - **API ID Path**: features_grid.default.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *FeaturesGrid → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Network with climate innovators worldwide...
   * - **API ID Path**: features_grid.default.primary.features[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Link field in *FeaturesGrid → Default → Primary → Features*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: features_grid.default.primary.features[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *FeaturesGrid → Default → Primary*
 */
export interface FeaturesGridSliceDefaultPrimary {
  /**
   * Features field in *FeaturesGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: features_grid.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<
    Simplify<FeaturesGridSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for FeaturesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default FeaturesGrid variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturesGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturesGrid*
 */
type FeaturesGridSliceVariation = FeaturesGridSliceDefault;

/**
 * FeaturesGrid Shared Slice
 *
 * - **API ID**: `features_grid`
 * - **Description**: 3-column grid of feature cards with icons, titles, descriptions, and links
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturesGridSlice = prismic.SharedSlice<
  "features_grid",
  FeaturesGridSliceVariation
>;

/**
 * Item in *Footer → Default → Primary → Footer Links*
 */
export interface FooterSliceDefaultPrimaryLinksItem {
  /**
   * Link Label field in *Footer → Default → Primary → Footer Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Privacy Policy
   * - **API ID Path**: footer.default.primary.links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link URL field in *Footer → Default → Primary → Footer Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.links[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Copyright Text field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: © 2025 Climate Solutions. All rights reserved.
   * - **API ID Path**: footer.default.primary.copyrightText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyrightText: prismic.KeyTextField;

  /**
   * Footer Links field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Footer variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Dark footer with copyright text and navigation links
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *FullScreenSection → full_screen_section → Primary*
 */
export interface FullScreenSectionSliceDefaultPrimary {
  /**
   * video_url field in *FullScreenSection → full_screen_section → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_screen_section.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  video_url: prismic.KeyTextField;
}

/**
 * full_screen_section variation for FullScreenSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullScreenSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullScreenSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FullScreenSection*
 */
type FullScreenSectionSliceVariation = FullScreenSectionSliceDefault;

/**
 * FullScreenSection Shared Slice
 *
 * - **API ID**: `full_screen_section`
 * - **Description**: FullScreenSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullScreenSectionSlice = prismic.SharedSlice<
  "full_screen_section",
  FullScreenSectionSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Tagline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Your Deep Dive Into
   * - **API ID Path**: hero.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;

  /**
   * Headline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Climate Change Solutions
   * - **API ID Path**: hero.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Explore global innovations, network with gamechangers...
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Call to Action Buttons field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Hero variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Full viewport hero section with gradient background, tagline, headline, subtitle, and CTA buttons
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CtaBannerSlice,
      CtaBannerSliceDefaultPrimary,
      CtaBannerSliceVariation,
      CtaBannerSliceDefault,
      FeaturesGridSlice,
      FeaturesGridSliceDefaultPrimaryFeaturesItem,
      FeaturesGridSliceDefaultPrimary,
      FeaturesGridSliceVariation,
      FeaturesGridSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimaryLinksItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      FullScreenSectionSlice,
      FullScreenSectionSliceDefaultPrimary,
      FullScreenSectionSliceVariation,
      FullScreenSectionSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
